### PR TITLE
feat(HIS): introduction to the HIS checker

### PR DESCRIPTION
**Pull request by AfonsoSantos96**
This is the introduction PR to add the HIS metric checker to the bao-ci workflow.
The HIS metrics define recommended thresholds for a set of key code quality metrics (explicit in afterward PRs).
This PR still does not include the checker script itself but prepares the CI structure to eventually run it.

### Type of change

- **feat**: introduces a new functionality
  - Logical unit: his_checker

## Checklist:

- [ ] The changes generate no new warnings when building the project. If so, I have justified above.
- [ ] I have run the CI checkers before submitting the PR to avoid unnecessary runs of the workflow.

### CODE REVIEW

**Review by josecm — CHANGES_REQUESTED** [review]
Since you have the invocation logic of the script in the makefile, I think you could add the base logic of parameter parsing in the python script for this PR.

**Comment by AfonsoSantos96** [comment]
> Since you have the invocation logic of the script in the makefile, I think you could add the base logic of parameter parsing in the python script for this PR.

Good idea! Just added it to the last commit

**Comment by josecm** [comment]
> > Since you have the invocation logic of the script in the makefile, I think you could add the base logic of parameter parsing in the python script for this PR.
> 
> Good idea! Just added it to the last commit

@AfonsoSantos96 I'd prefer to use [argparse](https://docs.python.org/3/library/argparse.html) in case the script evolves with further options...

**Comment by AfonsoSantos96** [comment]
> @AfonsoSantos96 I'd prefer to use [argparse](https://docs.python.org/3/library/argparse.html) in case the script evolves with further options...

Changed to `argparse`, thanks! 
To avoid an error on the `pylint` check, for now, I just inserted a print on the metrics checker function. This avoids the "unused argument" error.

**Review by josecm — APPROVED** [review]
LGTM! The only thing missing is having the *his_checker.py* file with execution permissions. 

I'd say you can already submit the next PR with the first rules check and set it as dependent to this one.

**Pull request closed without merging**
